"""initial schema

Revision ID: 21350710378b
Revises: 
Create Date: 2026-07-29 01:51:34.399937
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '21350710378b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('authority_type', sa.Enum('ministry', 'department', 'state_agency', 'bank', 'psu', 'implementing_agency', name='authority_type', native_enum=False), nullable=False),
    sa.Column('portal_url', sa.String(length=1000), nullable=True),
    sa.Column('contact', sa.String(length=300), nullable=True),
    sa.Column('document_acceptance_method', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authority')),
    sa.UniqueConstraint('slug', name=op.f('uq_authority_slug'))
    )
    op.create_table('scheme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme')),
    sa.UniqueConstraint('slug', name=op.f('uq_scheme_slug'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('email', name=op.f('uq_user_account_email'))
    )
    op.create_table('consent_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('scheme_matching', 'document_storage', 'outcome_analytics', 'notifications', name='consent_purpose', native_enum=False), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_consent_grant_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_grant')),
    sa.UniqueConstraint('user_id', 'purpose', name='uq_consent_grant_user_id_purpose')
    )
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_name', sa.String(length=300), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.Enum('idea', 'early', 'growth', 'mature', name='entity_stage', native_enum=False), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('is_woman_led', sa.Boolean(), nullable=True),
    sa.Column('registrations', sa.JSON(), nullable=False),
    sa.Column('annual_turnover_inr', sa.Text(), nullable=True),
    sa.Column('social_category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('employee_count IS NULL OR employee_count >= 0', name=op.f('ck_profile_employees_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_profile_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profile_user_id'))
    )
    op.create_table('scheme_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scheme_type', sa.Enum('grant', 'loan', 'subsidy', 'scholarship', 'tax_benefit', 'credit_guarantee', 'certification', 'equity', name='scheme_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'closed', name='scheme_status', native_enum=False), nullable=False),
    sa.Column('administering_ministry', sa.String(length=300), nullable=False),
    sa.Column('implementing_agency', sa.String(length=300), nullable=True),
    sa.Column('authority_id', sa.Uuid(), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('benefit_value_min', sa.Integer(), nullable=True),
    sa.Column('benefit_value_max', sa.Integer(), nullable=True),
    sa.Column('benefit_description', sa.Text(), nullable=False),
    sa.Column('application_url', sa.String(length=1000), nullable=True),
    sa.Column('offline_process', sa.Boolean(), nullable=False),
    sa.Column('application_difficulty', sa.Enum('low', 'medium', 'high', name='application_difficulty', native_enum=False), nullable=False),
    sa.Column('estimated_effort_hours', sa.Integer(), nullable=True),
    sa.Column('drafting_lead_days', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('benefit_value_max IS NULL OR benefit_value_min IS NULL OR benefit_value_max >= benefit_value_min', name=op.f('ck_scheme_version_benefit_range_ordered')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_scheme_version_version_positive')),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], name=op.f('fk_scheme_version_authority_id_authority'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_id'], ['scheme.id'], name=op.f('fk_scheme_version_scheme_id_scheme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheme_version')),
    sa.UniqueConstraint('scheme_id', 'version', name='uq_scheme_version_scheme_id_version')
    )
    op.create_index('ix_scheme_version_current', 'scheme_version', ['scheme_id', 'is_current'], unique=False)
    op.create_table('user_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_session_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    op.create_index('ix_user_session_user_id', 'user_session', ['user_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready_for_review', 'submitted', 'under_review', 'approved', 'rejected', 'withdrawn', name='application_status', native_enum=False), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_application_scheme_version_id_scheme_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_application_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application'))
    )
    op.create_table('application_window',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('open_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence', sa.Enum('annual', 'quarterly', 'rolling', 'one_time', name='recurrence', native_enum=False), nullable=False),
    sa.Column('notification_source', sa.Enum('gazette', 'pib', 'portal', 'circular', name='notification_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.CheckConstraint('open_date IS NULL OR close_date IS NULL OR close_date >= open_date', name=op.f('ck_application_window_window_dates_ordered')),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_application_window_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_window'))
    )
    op.create_table('benefit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('benefit_type', sa.Enum('cash', 'kind', 'service', 'recognition', 'credit_guarantee', 'interest_subvention', name='benefit_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantum_min', sa.Integer(), nullable=True),
    sa.Column('quantum_max', sa.Integer(), nullable=True),
    sa.Column('conditions_for_disbursement', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_benefit_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefit'))
    )
    op.create_table('document_requirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('issuing_authority_id', sa.Uuid(), nullable=True),
    sa.Column('issuing_authority_name', sa.String(length=300), nullable=True),
    sa.Column('typical_processing_days', sa.Integer(), nullable=True),
    sa.Column('how_to_obtain', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('conditional_logic', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['issuing_authority_id'], ['authority.id'], name=op.f('fk_document_requirement_issuing_authority_id_authority'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_document_requirement_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_requirement'))
    )
    op.create_table('eligibility_criterion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_type', sa.Enum('hard', 'soft', name='criterion_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('machine_readable_rule', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(criterion_type = 'hard' AND machine_readable_rule IS NOT NULL) OR (criterion_type = 'soft' AND machine_readable_rule IS NULL)", name=op.f('ck_eligibility_criterion_hard_criteria_require_rule')),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_eligibility_criterion_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_criterion'))
    )
    op.create_table('outcome',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_type', sa.Enum('approved', 'partially_approved', 'rejected', 'lapsed', name='outcome_type', native_enum=False), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_sanctioned_inr', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('days_to_decision', sa.Integer(), nullable=True),
    sa.Column('applicant_state', sa.String(length=80), nullable=True),
    sa.Column('applicant_sector', sa.String(length=120), nullable=True),
    sa.Column('applicant_turnover_band', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_outcome_application_id_application'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome')),
    sa.UniqueConstraint('application_id', name=op.f('uq_outcome_application_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome')
    op.drop_table('eligibility_criterion')
    op.drop_table('document_requirement')
    op.drop_table('benefit')
    op.drop_table('application_window')
    op.drop_table('application')
    op.drop_index('ix_user_session_user_id', table_name='user_session')
    op.drop_table('user_session')
    op.drop_index('ix_scheme_version_current', table_name='scheme_version')
    op.drop_table('scheme_version')
    op.drop_table('profile')
    op.drop_table('consent_grant')
    op.drop_table('user_account')
    op.drop_table('scheme')
    op.drop_table('authority')
    # ### end Alembic commands ###
