"""documents drafts applications crawl review queue

Revision ID: 25431b73466b
Revises: b15f87ac2693
Create Date: 2026-07-29 17:05:33.891013
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '25431b73466b'
down_revision: str | None = 'b15f87ac2693'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.Enum('static_html', 'js_rendered', 'pdf', name='crawl_source_type', native_enum=False), nullable=False),
    sa.Column('scheme_slug', sa.String(length=120), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_source')),
    sa.UniqueConstraint('url', name=op.f('uq_crawl_source_url'))
    )
    op.create_table('pending_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('previous_content_hash', sa.String(length=64), nullable=True),
    sa.Column('new_content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_content', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status', native_enum=False), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user_account.id'], name=op.f('fk_pending_revision_reviewed_by_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['crawl_source.id'], name=op.f('fk_pending_revision_source_id_crawl_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_revision'))
    )
    op.create_table('user_document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('dpiit_certificate', 'udyam_certificate', 'gst_certificate', 'pan_card', 'incorporation_certificate', 'audited_financials', 'bank_statement', 'pitch_deck', 'project_report', 'caste_certificate', 'income_certificate', 'land_record', 'noc', 'unknown', name='vault_document_type', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('issuing_authority_name', sa.String(length=300), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('confirmed_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR issue_date IS NULL OR expiry_date >= issue_date', name=op.f('ck_user_document_expiry_after_issue')),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_document_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_document'))
    )
    op.create_table('application_draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_application_draft_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_application_draft_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_draft')),
    sa.UniqueConstraint('user_id', 'scheme_version_id', 'version', name='uq_application_draft_user_scheme_version')
    )
    op.create_index('ix_application_draft_current', 'application_draft', ['user_id', 'scheme_version_id', 'is_current'], unique=False)
    op.create_table('deadline_notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_version_id', sa.Uuid(), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_version_id'], ['scheme_version.id'], name=op.f('fk_deadline_notification_scheme_version_id_scheme_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_deadline_notification_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deadline_notification')),
    sa.UniqueConstraint('user_id', 'scheme_version_id', 'offset_days', name='uq_deadline_notification_user_scheme_offset')
    )
    # Existing accounts need an explicit value before the column can become
    # non-null. A server default would leak a migration concern into the live
    # schema, so backfill in three portable steps instead.
    op.add_column('user_account', sa.Column('is_reviewer', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE user_account SET is_reviewer = false WHERE is_reviewer IS NULL"))
    with op.batch_alter_table('user_account') as batch_op:
        batch_op.alter_column('is_reviewer', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'is_reviewer')
    op.drop_table('deadline_notification')
    op.drop_index('ix_application_draft_current', table_name='application_draft')
    op.drop_table('application_draft')
    op.drop_table('user_document')
    op.drop_table('pending_revision')
    op.drop_table('crawl_source')
    # ### end Alembic commands ###
