"""ai judgement audit trail

Revision ID: b15f87ac2693
Revises: 21350710378b
Create Date: 2026-07-29 02:32:34.321501
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b15f87ac2693'
down_revision: str | None = '21350710378b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_judgement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.Enum('likely_met', 'likely_unmet', 'uncertain', name='soft_verdict', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_that_would_strengthen', sa.JSON(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['eligibility_criterion.id'], name=op.f('fk_ai_judgement_criterion_id_eligibility_criterion'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_ai_judgement_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_judgement'))
    )
    op.create_index('ix_ai_judgement_cache_key', 'ai_judgement', ['cache_key'], unique=True)
    op.create_index('ix_ai_judgement_user_id', 'ai_judgement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_judgement_user_id', table_name='ai_judgement')
    op.drop_index('ix_ai_judgement_cache_key', table_name='ai_judgement')
    op.drop_table('ai_judgement')
    # ### end Alembic commands ###
