/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Report only whether the API process can serve requests.
         *
         *     This deliberately has no database dependency, so an orchestrator does not
         *     restart a healthy process merely because a downstream service is unavailable.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Report whether dependencies required to serve application traffic work.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Backward-compatible readiness endpoint for existing deployments.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Schemes
         * @description List the current version of every scheme, newest curation first.
         */
        get: operations["list_schemes_schemes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheme
         * @description Retrieve one scheme revision with all of its sourced claims.
         *
         *     Historical revisions remain retrievable so an assessment made months ago can
         *     still be explained against the criteria that were in force at the time.
         */
        get: operations["get_scheme_schemes__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freshness/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Freshness
         * @description Staleness report for the current version of every scheme.
         *
         *     Sorted oldest-verified-first, so the schemes most in need of a human
         *     recheck surface at the top rather than being buried in an alphabetical
         *     list.
         */
        get: operations["list_freshness_freshness__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/freshness/{scheme_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Freshness
         * @description Staleness report for one scheme's current version.
         */
        get: operations["get_freshness_freshness__scheme_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account, record consent, and start a session.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke every session for the user, not just the current one.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        /**
         * Erase Account
         * @description Delete the account and all personal data associated with it.
         *
         *     Outcome rows survive in de-identified form. They carry state, sector and a
         *     coarse turnover band, never an exact figure and never a link to a person, so
         *     they remain useful for improving recommendations without being personal data.
         */
        delete: operations["erase_account_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consents */
        get: operations["list_consents_me_consents_get"];
        put?: never;
        /**
         * Update Consent
         * @description Grant or withdraw consent for one purpose.
         *
         *     Withdrawing ``scheme_matching`` is allowed and deletes the profile, because
         *     the profile exists only to be matched. Silently keeping it after consent is
         *     withdrawn would make the consent meaningless.
         */
        post: operations["update_consent_me_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_profile_get"];
        /**
         * Upsert Profile
         * @description Create or replace the profile.
         *
         *     One profile per account in v1. Idempotent, so a client retrying after a
         *     dropped connection does not create a duplicate.
         */
        put: operations["upsert_profile_profile_put"];
        post?: never;
        /**
         * Delete Profile
         * @description Delete the profile while keeping the account.
         *
         *     Separate from account erasure on purpose: a user may want to remove their
         *     business details without giving up the account.
         */
        delete: operations["delete_profile_profile_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/draftable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Draftable Schemes */
        get: operations["list_draftable_schemes_matches_draftable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{slug}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Draft */
        get: operations["get_current_draft_matches__slug__draft_get"];
        put?: never;
        /**
         * Create Draft
         * @description Generate a new draft version for one scheme.
         *
         *     Every call creates a new version rather than overwriting, so an applicant can
         *     see what changed between attempts. Nothing here submits anything — see the
         *     module docstring on :mod:`bharat_os.services.drafting`.
         */
        post: operations["create_draft_matches__slug__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Rank every active scheme against the caller's profile.
         *
         *     Assessment is deterministic: hard criteria only, evaluated in code. Criteria
         *     requiring judgement are counted and reported as outstanding rather than
         *     guessed at.
         */
        get: operations["list_matches_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match
         * @description The assessment for one scheme against the caller's profile.
         */
        get: operations["get_match_matches__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{slug}/deep-dive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deep Dive
         * @description The full, sourced, auditable breakdown for one scheme.
         *
         *     Every criterion here traces back to a source URL and a verification date; every
         *     soft judgement traces back to the exact prompt and model that produced it. This
         *     is the answer to "how do I know this isn't hallucinating".
         */
        get: operations["get_deep_dive_matches__slug__deep_dive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Add Document */
        post: operations["add_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{slug}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Checklist
         * @description Have / need / expired / not-applicable for one scheme's requirements.
         */
        get: operations["get_document_checklist_matches__slug__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Deadline Calendar
         * @description Return every non-ruled-out scheme with a deadline reachability verdict.
         */
        get: operations["get_deadline_calendar_deadlines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deadlines/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Deadline Calendar
         * @description Download the caller's reachable deadline plan for any calendar application.
         */
        get: operations["export_deadline_calendar_deadlines_calendar_ics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{slug}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Application
         * @description Start tracking an application. Created in DRAFT; nothing is submitted.
         */
        post: operations["start_application_matches__slug__applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Application Status
         * @description Record a status change the user is telling us about.
         *
         *     Moving to SUBMITTED means the user has told us they filed it themselves
         *     through the official channel; the system does not and cannot cause this
         *     transition on its own initiative.
         */
        patch: operations["update_application_status_applications__application_id__patch"];
        trace?: never;
    };
    "/applications/{application_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Outcome
         * @description Record what happened. This is the data asset the long-term thesis rests on.
         *
         *     Exact turnover never reaches this row — it is banded at the point of capture,
         *     here, so de-identification is enforced rather than merely intended.
         */
        post: operations["record_outcome_applications__application_id__outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/{slug}/outcome-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheme Outcome Stats
         * @description Aggregate outcome statistics. Never a per-applicant row.
         *
         *     Available to any signed-in user, since the aggregate itself contains nothing
         *     that identifies a contributor — that is the entire point of banding and
         *     de-identifying at capture time.
         */
        get: operations["get_scheme_outcome_stats_schemes__slug__outcome_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description Everything awaiting a decision, oldest first — first in, first reviewed.
         *
         *     A queue that becomes a bottleneck is a documented failure mode for this kind
         *     of product, so ordering favours clearing the backlog over any other sort.
         */
        get: operations["list_pending_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{revision_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Revision */
        post: operations["approve_revision_review_queue__revision_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{revision_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Revision */
        post: operations["reject_revision_review_queue__revision_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue/{revision_id}/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotate Revision
         * @description Leave a note without deciding — for flagging something to a colleague.
         */
        post: operations["annotate_revision_review_queue__revision_id__annotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountOut
         * @description The authenticated user's own account. Never exposes another user's data.
         */
        AccountOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Consents */
            consents: components["schemas"]["ConsentOut"][];
            /** Has Profile */
            has_profile: boolean;
        };
        /** AnnotateIn */
        AnnotateIn: {
            /** Note */
            note: string;
        };
        /**
         * ApplicationDifficulty
         * @description How hard the application is, used to discount the ranking score.
         * @enum {string}
         */
        ApplicationDifficulty: "low" | "medium" | "high";
        /** ApplicationOut */
        ApplicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            status: components["schemas"]["ApplicationStatus"];
            /** External Reference */
            external_reference: string | null;
            /** Submitted At */
            submitted_at: string | null;
            /** Last Status Update */
            last_status_update: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ApplicationStatus
         * @description Lifecycle of a user's application.
         *
         *     Transitions past ``READY_FOR_REVIEW`` are always user-initiated. Nothing in
         *     the system advances an application to ``SUBMITTED`` on its own.
         * @enum {string}
         */
        ApplicationStatus: "draft" | "ready_for_review" | "submitted" | "under_review" | "approved" | "rejected" | "withdrawn";
        /**
         * ApplicationStatusUpdateIn
         * @description A status change the user is making themselves.
         *
         *     ``external_reference`` is the reference number the government portal gave the
         *     user after *they* submitted — evidence that a human acted, not something the
         *     system fabricates.
         */
        ApplicationStatusUpdateIn: {
            status: components["schemas"]["ApplicationStatus"];
            /** External Reference */
            external_reference?: string | null;
        };
        /** ApplicationWindowOut */
        ApplicationWindowOut: {
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Open Date */
            open_date: string | null;
            /** Close Date */
            close_date: string | null;
            recurrence: components["schemas"]["Recurrence"];
            notification_source: components["schemas"]["NotificationSource"];
            /** Notes */
            notes: string | null;
            /** Days Since Verified */
            readonly days_since_verified: number;
        };
        /** AuthorityOut */
        AuthorityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            authority_type: components["schemas"]["AuthorityType"];
            /** Portal Url */
            portal_url: string | null;
        };
        /**
         * AuthorityType
         * @enum {string}
         */
        AuthorityType: "ministry" | "department" | "state_agency" | "bank" | "psu" | "implementing_agency";
        /** BenefitOut */
        BenefitOut: {
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            benefit_type: components["schemas"]["BenefitType"];
            /** Description */
            description: string;
            /** Quantum Min */
            quantum_min: number | null;
            /** Quantum Max */
            quantum_max: number | null;
            /** Conditions For Disbursement */
            conditions_for_disbursement: string | null;
            /** Days Since Verified */
            readonly days_since_verified: number;
        };
        /**
         * BenefitType
         * @enum {string}
         */
        BenefitType: "cash" | "kind" | "service" | "recognition" | "credit_guarantee" | "interest_subvention";
        /** ConsentOut */
        ConsentOut: {
            purpose: components["schemas"]["ConsentPurpose"];
            /** Granted At */
            granted_at: string | null;
            /** Withdrawn At */
            withdrawn_at: string | null;
            /** Policy Version */
            policy_version: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ConsentPurpose
         * @description Purposes a user consents to individually.
         *
         *     The DPDP Act requires consent to be specific and purpose-limited, so consent
         *     is recorded per purpose rather than as a single blanket acceptance. Only
         *     ``SCHEME_MATCHING`` is required to use the product; the rest are genuinely
         *     optional and the product must remain usable without them.
         * @enum {string}
         */
        ConsentPurpose: "scheme_matching" | "document_storage" | "outcome_analytics" | "notifications";
        /** ConsentUpdateIn */
        ConsentUpdateIn: {
            purpose: components["schemas"]["ConsentPurpose"];
            /** Granted */
            granted: boolean;
        };
        /**
         * CrawlSourceType
         * @enum {string}
         */
        CrawlSourceType: "static_html" | "js_rendered" | "pdf";
        /**
         * CriterionType
         * @description Whether a criterion is machine-decidable or requires judgement.
         *
         *     ``HARD`` criteria are evaluated deterministically in code. ``SOFT`` criteria
         *     require language judgement and are evaluated by an LLM with an explicit
         *     confidence score, never presented as fact.
         * @enum {string}
         */
        CriterionType: "hard" | "soft";
        /** DeadlineCalendarOut */
        DeadlineCalendarOut: {
            /** Deadlines */
            deadlines: components["schemas"]["DeadlineOut"][];
            /** Unreachable Count */
            unreachable_count: number;
        };
        /**
         * DeadlineOut
         * @description One scheme's deadline, with a reachability verdict rather than just a date.
         */
        DeadlineOut: {
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            status: components["schemas"]["ReachabilityStatus"];
            /** Close Date */
            close_date: string | null;
            /** Days Remaining */
            days_remaining: number | null;
            /** Days Required */
            days_required: number | null;
            /** Margin Days */
            margin_days: number | null;
            /** Bottleneck Document */
            bottleneck_document: string | null;
            /** Bottleneck Days */
            bottleneck_days: number | null;
        };
        /**
         * DeepDiveOut
         * @description The full eligibility breakdown for one scheme against one profile.
         */
        DeepDiveOut: {
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Scheme Type */
            scheme_type: string;
            outcome: components["schemas"]["ReportOutcome"];
            /** Confidence */
            confidence?: number | null;
            /** Disqualifications */
            disqualifications: components["schemas"]["DisqualificationOut"][];
            /** Met */
            met: components["schemas"]["HardCriterionOut"][];
            /** Unmet */
            unmet: components["schemas"]["HardCriterionOut"][];
            /** Unverifiable */
            unverifiable: components["schemas"]["HardCriterionOut"][];
            /** Soft */
            soft: components["schemas"]["SoftCriterionOut"][];
            /** Missing Fields */
            missing_fields: string[];
            /** Evidence Requested */
            evidence_requested: string[];
            /** Requires Human Review */
            requires_human_review: boolean;
            /** Has Stale Data */
            has_stale_data: boolean;
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * DisqualificationOut
         * @description Why an applicant cannot have this scheme, shown plainly rather than scored.
         */
        DisqualificationOut: {
            /**
             * Criterion Id
             * Format: uuid
             */
            criterion_id: string;
            /** Description */
            description: string;
            /** Reason */
            reason: string;
        };
        /**
         * DocumentChecklistOut
         * @description The full document picture for one scheme.
         */
        DocumentChecklistOut: {
            /** Slug */
            slug: string;
            /** Documents */
            documents: components["schemas"]["DocumentGapOut"][];
            /** Have Count */
            have_count: number;
            /** Need Count */
            need_count: number;
            /** Optional Missing Count */
            optional_missing_count: number;
            /** Expired Count */
            expired_count: number;
            /** Unused Vault Documents */
            unused_vault_documents: components["schemas"]["UserDocumentOut"][];
        };
        /** DocumentGapOut */
        DocumentGapOut: {
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            /** Document Name */
            document_name: string;
            /** Document Type */
            document_type: string;
            /** Mandatory */
            mandatory: boolean;
            status: components["schemas"]["DocumentStatus"];
            /** Issuing Authority */
            issuing_authority: string | null;
            /** Typical Processing Days */
            typical_processing_days: number | null;
            /** How To Obtain */
            how_to_obtain: string | null;
            /** Expired On */
            expired_on: string | null;
        };
        /** DocumentRequirementOut */
        DocumentRequirementOut: {
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Document Name */
            document_name: string;
            /** Document Type */
            document_type: string;
            /** Issuing Authority Name */
            issuing_authority_name: string | null;
            /** Typical Processing Days */
            typical_processing_days: number | null;
            /** How To Obtain */
            how_to_obtain: string | null;
            /** Mandatory */
            mandatory: boolean;
            /** Conditional Logic */
            conditional_logic: Record<string, never> | null;
            /** Display Order */
            display_order: number;
            /** Days Since Verified */
            readonly days_since_verified: number;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "have" | "need" | "expired" | "not_applicable" | "optional_missing";
        /**
         * DocumentType
         * @description Document kinds the vault understands.
         *
         *     ``UNKNOWN`` is deliberate: an unrecognised document is flagged for human
         *     classification rather than guessed at.
         * @enum {string}
         */
        DocumentType: "dpiit_certificate" | "udyam_certificate" | "gst_certificate" | "pan_card" | "incorporation_certificate" | "audited_financials" | "bank_statement" | "pitch_deck" | "project_report" | "caste_certificate" | "income_certificate" | "land_record" | "noc" | "unknown";
        /** DraftFieldOut */
        DraftFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            source: components["schemas"]["DraftFieldSource"];
            /** Value */
            value: string | null;
            /** Instruction */
            instruction?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * DraftFieldSource
         * @description Where a draft's field value came from.
         * @enum {string}
         */
        DraftFieldSource: "profile" | "generated_narrative" | "human_required";
        /** DraftOut */
        DraftOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Version */
            version: number;
            /** Fields */
            fields: components["schemas"]["DraftFieldOut"][];
            /** Human Required Count */
            human_required_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Review Notice
             * @default This is a draft, not a submission. Review every field, complete the ones marked for you, and submit it yourself through the official channel. Nothing here files anything on your behalf.
             */
            review_notice: string;
        };
        /** EligibilityCriterionOut */
        EligibilityCriterionOut: {
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            criterion_type: components["schemas"]["CriterionType"];
            /** Description */
            description: string;
            /** Machine Readable Rule */
            machine_readable_rule: Record<string, never> | null;
            /** Display Order */
            display_order: number;
            /** Days Since Verified */
            readonly days_since_verified: number;
        };
        /**
         * EntityStage
         * @enum {string}
         */
        EntityStage: "idea" | "early" | "growth" | "mature";
        /**
         * ErasureOut
         * @description Confirmation of what a deletion actually removed.
         *
         *     Reporting the counts matters: "your data is deleted" is a claim the user has
         *     no way to check, and a vague confirmation is how erasure quietly fails.
         */
        ErasureOut: {
            /** Account Deleted */
            account_deleted: boolean;
            /** Profile Deleted */
            profile_deleted: boolean;
            /** Sessions Revoked */
            sessions_revoked: number;
            /** Consents Deleted */
            consents_deleted: number;
            /** Ai Judgements Deleted */
            ai_judgements_deleted: number;
            /** Applications Unlinked */
            applications_unlinked: number;
            /** Outcomes Retained Anonymised */
            outcomes_retained_anonymised: number;
            /** Note */
            note: string;
        };
        /**
         * EvaluationState
         * @description Outcome of evaluating a single criterion.
         *
         *     ``CANNOT_VERIFY`` is always preferred over guessing: it means the profile
         *     lacks the information needed to decide, which is materially different from
         *     the criterion being unmet.
         * @enum {string}
         */
        EvaluationState: "met" | "unmet" | "cannot_verify";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardCriterionOut
         * @description One deterministic criterion, with its verdict and provenance.
         */
        HardCriterionOut: {
            /**
             * Criterion Id
             * Format: uuid
             */
            criterion_id: string;
            /** Description */
            description: string;
            state: components["schemas"]["EvaluationState"];
            /** Reason */
            reason: string;
            /** Missing Fields */
            missing_fields: string[];
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /** Days Since Verified */
            days_since_verified: number;
            /** Is Stale */
            is_stale: boolean;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Environment */
            environment: string;
            /**
             * Database
             * @enum {string}
             */
            database: "reachable" | "unreachable";
            /** Scheme Count */
            scheme_count?: number | null;
        };
        /** LivenessOut */
        LivenessOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MatchFeedOut
         * @description The ranked feed, with ruled-out schemes kept separate.
         */
        MatchFeedOut: {
            /** Matches */
            matches: components["schemas"]["MatchOut"][];
            /** Ruled Out */
            ruled_out: components["schemas"]["MatchOut"][];
            /** Schemes Assessed */
            schemes_assessed: number;
            /** Suggested Profile Additions */
            suggested_profile_additions: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * MatchOut
         * @description One scheme as it appears in the ranked feed.
         */
        MatchOut: {
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            scheme_type: components["schemas"]["SchemeType"];
            /** Administering Ministry */
            administering_ministry: string;
            outcome: components["schemas"]["MatchOutcome"];
            /** Confidence */
            confidence: number;
            /** Score */
            score: number;
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** Criteria Met */
            criteria_met: number;
            /** Criteria Unmet */
            criteria_unmet: number;
            /** Criteria Unverifiable */
            criteria_unverifiable: number;
            /** Soft Criteria Count */
            soft_criteria_count: number;
            /** Missing Fields */
            missing_fields: string[];
            /** Benefit Description */
            benefit_description: string;
            /** Benefit Value Max */
            benefit_value_max: number | null;
            application_difficulty: components["schemas"]["ApplicationDifficulty"];
            /** Application Url */
            application_url: string | null;
            /** Estimated Effort Hours */
            estimated_effort_hours: number | null;
            /** Next Deadline */
            next_deadline: string | null;
            /** Max Days Since Verified */
            max_days_since_verified: number;
        };
        /**
         * MatchOutcome
         * @description How a scheme relates to an applicant.
         *
         *     Kept distinct from the score so the interface can say "you are ruled out
         *     because X" instead of showing a low percentage and leaving the user guessing.
         * @enum {string}
         */
        MatchOutcome: "eligible" | "needs_more_data" | "ruled_out" | "judgement_only";
        /**
         * NotificationSource
         * @description Where an application window was published.
         * @enum {string}
         */
        NotificationSource: "gazette" | "pib" | "portal" | "circular";
        /** OutcomeIn */
        OutcomeIn: {
            outcome_type: components["schemas"]["OutcomeType"];
            /** Decided At */
            decided_at?: string | null;
            /** Amount Sanctioned Inr */
            amount_sanctioned_inr?: number | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** OutcomeOut */
        OutcomeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            outcome_type: components["schemas"]["OutcomeType"];
            /** Decided At */
            decided_at: string | null;
            /** Amount Sanctioned Inr */
            amount_sanctioned_inr: number | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Notes */
            notes: string | null;
            /** Days To Decision */
            days_to_decision: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OutcomeType
         * @enum {string}
         */
        OutcomeType: "approved" | "partially_approved" | "rejected" | "lapsed";
        /** PendingRevisionOut */
        PendingRevisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Url */
            source_url: string;
            source_type: components["schemas"]["CrawlSourceType"];
            /** Scheme Slug */
            scheme_slug: string | null;
            status: components["schemas"]["ReviewStatus"];
            /** Extracted Content */
            extracted_content: Record<string, never>;
            /** Extraction Confidence */
            extraction_confidence: number | null;
            /** Review Note */
            review_note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProfileIn
         * @description Applicant profile.
         *
         *     Only fields that some criterion in the knowledge base actually reads are
         *     collected. Data minimisation is a legal obligation under the DPDP Act and
         *     also a design constraint: an unused field is pure liability.
         */
        ProfileIn: {
            /** Entity Name */
            entity_name: string;
            /** State */
            state: string;
            /** District */
            district?: string | null;
            /** Sector */
            sector: string;
            stage: components["schemas"]["EntityStage"];
            /** Employee Count */
            employee_count?: number | null;
            /** Incorporation Date */
            incorporation_date?: string | null;
            /** Is Woman Led */
            is_woman_led?: boolean | null;
            /** Registrations */
            registrations?: components["schemas"]["RegistrationType"][];
            /** Annual Turnover Inr */
            annual_turnover_inr?: number | null;
            social_category?: components["schemas"]["SocialCategory"] | null;
        };
        /**
         * ProfileOut
         * @description A profile as returned to its owner.
         *
         *     Sensitive fields are included because the owner is entitled to see their own
         *     data, but they are never logged and never returned to anyone else.
         */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Entity Name */
            entity_name: string;
            /** State */
            state: string;
            /** District */
            district: string | null;
            /** Sector */
            sector: string;
            stage: components["schemas"]["EntityStage"];
            /** Employee Count */
            employee_count: number | null;
            /** Incorporation Date */
            incorporation_date: string | null;
            /** Is Woman Led */
            is_woman_led: boolean | null;
            /** Registrations */
            registrations: string[];
            /** Annual Turnover Inr */
            annual_turnover_inr: number | null;
            /** Social Category */
            social_category: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReachabilityStatus
         * @enum {string}
         */
        ReachabilityStatus: "comfortable" | "tight" | "unreachable" | "closed" | "no_deadline";
        /**
         * Recurrence
         * @enum {string}
         */
        Recurrence: "annual" | "quarterly" | "rolling" | "one_time";
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Consents */
            consents?: components["schemas"]["ConsentPurpose"][];
        };
        /**
         * RegistrationType
         * @description Government registrations an applicant may hold.
         *
         *     Many schemes gate eligibility on these, so they are first-class rather than
         *     free text.
         * @enum {string}
         */
        RegistrationType: "dpiit" | "udyam" | "gst" | "fcra" | "msme_uam" | "company_incorporation";
        /** RejectDecisionIn */
        RejectDecisionIn: {
            /** Note */
            note: string;
        };
        /**
         * ReportOutcome
         * @description The headline conclusion of an assessment.
         * @enum {string}
         */
        ReportOutcome: "ruled_out" | "strong" | "promising" | "insufficient_data" | "needs_human_review";
        /** ReviewDecisionIn */
        ReviewDecisionIn: {
            /** Note */
            note?: string | null;
        };
        /**
         * ReviewStatus
         * @description State of a machine-detected change awaiting human judgement.
         *
         *     Nothing produced by a crawler or extractor reaches the live scheme corpus
         *     without passing through ``APPROVED`` here. That is enforced by the loader
         *     only ever being called on hand-curated or approved data, never on raw
         *     crawl output.
         * @enum {string}
         */
        ReviewStatus: "pending" | "approved" | "rejected";
        /**
         * SchemeDetailOut
         * @description Full scheme version, including every sourced claim.
         */
        SchemeDetailOut: {
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Slug */
            slug: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            scheme_type: components["schemas"]["SchemeType"];
            status: components["schemas"]["SchemeStatus"];
            /** Administering Ministry */
            administering_ministry: string;
            /** Target Segments */
            target_segments: string[];
            /** Sectors */
            sectors: string[];
            /** States */
            states: string[];
            /** Benefit Value Min */
            benefit_value_min: number | null;
            /** Benefit Value Max */
            benefit_value_max: number | null;
            /** Benefit Description */
            benefit_description: string;
            application_difficulty: components["schemas"]["ApplicationDifficulty"];
            /** Offline Process */
            offline_process: boolean;
            /** Implementing Agency */
            implementing_agency: string | null;
            /** Application Url */
            application_url: string | null;
            /** Estimated Effort Hours */
            estimated_effort_hours: number | null;
            /** Drafting Lead Days */
            drafting_lead_days: number;
            /**
             * Effective From
             * Format: date-time
             */
            effective_from: string;
            authority: components["schemas"]["AuthorityOut"] | null;
            /** Criteria */
            criteria: components["schemas"]["EligibilityCriterionOut"][];
            /** Document Requirements */
            document_requirements: components["schemas"]["DocumentRequirementOut"][];
            /** Windows */
            windows: components["schemas"]["ApplicationWindowOut"][];
            /** Benefits */
            benefits: components["schemas"]["BenefitOut"][];
        };
        /**
         * SchemeFreshnessOut
         * @description Staleness of one scheme's sourced criteria, oldest claim first.
         */
        SchemeFreshnessOut: {
            /** Scheme Slug */
            scheme_slug: string;
            /** Scheme Name */
            scheme_name: string;
            /** Oldest Criterion Verified At */
            oldest_criterion_verified_at: string | null;
            /** Is Stale */
            is_stale: boolean;
            /** Days Since Last Verification */
            days_since_last_verification: number | null;
            /** Stale Criterion Count */
            stale_criterion_count: number;
            /** Total Criterion Count */
            total_criterion_count: number;
            /** Staleness Threshold Days */
            staleness_threshold_days: number;
        };
        /**
         * SchemeOutcomeStatsOut
         * @description Aggregate statistics only. Never a per-applicant row.
         */
        SchemeOutcomeStatsOut: {
            /** Scheme Version Id */
            scheme_version_id: string;
            /** Total */
            total: number;
            /** Approved */
            approved: number;
            /** Rejected */
            rejected: number;
            /** Approval Rate */
            approval_rate: number | null;
            /** Common Rejection Reasons */
            common_rejection_reasons: [
                string,
                number
            ][];
        };
        /**
         * SchemeStatus
         * @enum {string}
         */
        SchemeStatus: "active" | "paused" | "closed";
        /**
         * SchemeSummaryOut
         * @description Compact scheme representation for list endpoints.
         */
        SchemeSummaryOut: {
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Slug */
            slug: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
            scheme_type: components["schemas"]["SchemeType"];
            status: components["schemas"]["SchemeStatus"];
            /** Administering Ministry */
            administering_ministry: string;
            /** Target Segments */
            target_segments: string[];
            /** Sectors */
            sectors: string[];
            /** States */
            states: string[];
            /** Benefit Value Min */
            benefit_value_min: number | null;
            /** Benefit Value Max */
            benefit_value_max: number | null;
            /** Benefit Description */
            benefit_description: string;
            application_difficulty: components["schemas"]["ApplicationDifficulty"];
            /** Offline Process */
            offline_process: boolean;
        };
        /**
         * SchemeType
         * @enum {string}
         */
        SchemeType: "grant" | "loan" | "subsidy" | "scholarship" | "tax_benefit" | "credit_guarantee" | "certification" | "equity";
        /**
         * ScoreBreakdown
         * @description The factors behind a score.
         *
         *     Exposed rather than hidden. A ranking a user cannot interrogate is a ranking
         *     they have no reason to trust, and "why is this first?" is a fair question.
         */
        ScoreBreakdown: {
            /** Confidence Factor */
            confidence_factor: number;
            /** Benefit Factor */
            benefit_factor: number;
            /** Difficulty Factor */
            difficulty_factor: number;
        };
        /**
         * Segment
         * @description Beneficiary segment a scheme targets.
         *
         *     v1 curation covers ``STARTUP`` and ``MSME`` only. The remaining members
         *     exist so later curation needs no migration.
         * @enum {string}
         */
        Segment: "startup" | "msme" | "student" | "farmer" | "ngo" | "researcher" | "women_entrepreneur";
        /**
         * SocialCategory
         * @enum {string}
         */
        SocialCategory: "general" | "obc" | "sc" | "st" | "ews";
        /**
         * SoftCriterionOut
         * @description One judgement-based criterion, with the audit trail visible.
         */
        SoftCriterionOut: {
            /** Criterion Id */
            criterion_id: string;
            /** Description */
            description: string;
            verdict: components["schemas"]["SoftVerdict"];
            /** Confidence */
            confidence: number;
            /** Reasoning */
            reasoning: string;
            /** Evidence That Would Strengthen */
            evidence_that_would_strengthen: string[];
            /** Requires Human Review */
            requires_human_review: boolean;
            /** Audit Prompt */
            audit_prompt: string | null;
            /** Audit Provider */
            audit_provider: string;
            /** Audit Model */
            audit_model: string;
            /** Audit Prompt Version */
            audit_prompt_version: string;
            /** Was Cached */
            was_cached: boolean;
            /** Source Url */
            source_url: string;
            /** Source Quote */
            source_quote: string | null;
            /**
             * Last Verified At
             * Format: date-time
             */
            last_verified_at: string;
            /** Verified By Human */
            verified_by_human: boolean;
            /** Days Since Verified */
            days_since_verified: number;
            /** Is Stale */
            is_stale: boolean;
        };
        /**
         * SoftVerdict
         * @description A language model's judgement on a criterion requiring interpretation.
         *
         *     Deliberately hedged wording. A model reading a profile against "innovative
         *     technology-based startup" is forming an opinion, not making a finding, and the
         *     vocabulary should not let that opinion be mistaken for the latter. There is no
         *     plain ``met`` member for exactly that reason.
         * @enum {string}
         */
        SoftVerdict: "likely_met" | "likely_unmet" | "uncertain";
        /** SupportedSchemesOut */
        SupportedSchemesOut: {
            /** Slugs */
            slugs: string[];
        };
        /** UserDocumentIn */
        UserDocumentIn: {
            document_type: components["schemas"]["DocumentType"];
            /** Label */
            label?: string | null;
            /** Issuing Authority Name */
            issuing_authority_name?: string | null;
            /** Issue Date */
            issue_date?: string | null;
            /** Expiry Date */
            expiry_date?: string | null;
        };
        /** UserDocumentOut */
        UserDocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            document_type: components["schemas"]["DocumentType"];
            /** Label */
            label: string | null;
            /** Issuing Authority Name */
            issuing_authority_name: string | null;
            /** Issue Date */
            issue_date: string | null;
            /** Expiry Date */
            expiry_date: string | null;
            /** Is Expired */
            is_expired: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessOut"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_schemes_schemes_get: {
        parameters: {
            query?: {
                /** @description Filter by targeted segment */
                segment?: components["schemas"]["Segment"] | null;
                /** @description Filter to schemes available in this state, including all-India schemes */
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheme_schemes__slug__get: {
        parameters: {
            query?: {
                /** @description Specific revision to retrieve. Defaults to the current one. */
                version?: number | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_freshness_freshness__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeFreshnessOut"][];
                };
            };
        };
    };
    get_freshness_freshness__scheme_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheme_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeFreshnessOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_account_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_me_consents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_consent_me_consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_profile_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_profile_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_draftable_schemes_matches_draftable_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedSchemesOut"];
                };
            };
        };
    };
    get_current_draft_matches__slug__draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_draft_matches__slug__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches_get: {
        parameters: {
            query?: {
                /** @description Exclude matches below this confidence. */
                min_confidence?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchFeedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_matches__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deep_dive_matches__slug__deep_dive_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepDiveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDocumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_checklist_matches__slug__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChecklistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deadline_calendar_deadlines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadlineCalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_deadline_calendar_deadlines_calendar_ics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_application_matches__slug__applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_status_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_outcome_applications__application_id__outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheme_outcome_stats_schemes__slug__outcome_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemeOutcomeStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRevisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_revision_review_queue__revision_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_revision_review_queue__revision_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_revision_review_queue__revision_id__annotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: {
                bharat_os_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
